# @package _global_

defaults:
  - logger: offline
  - data: smoke
  - model: avici_smoke
  - trainer: smoke
  - inference: smoke
  - _self_
  - override hydra/job_logging: console

# Minimal default config for installed usage (
# `causal-meta` or `python -m causal_meta.main`).
name: "smoke_test"

hydra:
  run:
    dir: ${oc.env:CAUSAL_META_RUN_DIR,experiments/runs/${name}/${model.id}}
  sweep:
    dir: ${oc.env:CAUSAL_META_SWEEP_DIR,experiments/runs/${name}}
    subdir: ${model.id}
  output_subdir: null
