# @package inference

n_samples: 3
auc_num_shuffles: 1000
auc_balance_classes: true
auc_seed: 0
use_cached_inference: true
cache_inference: true

cache_compress: false
cache_dtype: "uint8"
cache_n_samples: null
